### ISSUE TITLE
Undeclared dependency on setuptools

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3748]
coala uses `pkg_resources`, which is part of `setuptools`, which is not a declared dependency.

Testing on setuptools 8.0 results in failures:

```
FAIL tests/coalaJSONTest.py::coalaJSONTest::test_version_conflict_in_collecting_bears
FAIL tests/coalaTest.py::coalaTest::test_unimportable_bear
FAIL tests/coalaTest.py::coalaTest::test_version_conflict_in_collecting_bears
FAIL tests/misc/ExceptionsTest.py::ExceptionsTest::test_get_exitcode


log_printer = <coalib.output.printers.LogPrinter.LogPrinter object at 0x7fe146f6e278>

    def get_exitcode(exception, log_printer=None):
        log_printer = (LogPrinter(NullPrinter()) if log_printer is None
                       else log_printer)

        if isinstance(exception, KeyboardInterrupt):  # Ctrl+C
            print('Program terminated by user.')
            exitcode = 130
        elif isinstance(exception, EOFError):  # Ctrl+D
            print('Found EOF. Exiting gracefully.')
            exitcode = 0
        elif isinstance(exception, SystemExit):
            exitcode = exception.code
        elif isinstance(exception, VersionConflict):
>           log_message = Constants.VERSION_CONFLICT_MESSAGE % str(exception.req)

E           AttributeError: 'VersionConflict' object has no attribute 'req'
```
https://travis-ci.org/jayvdb/coala/jobs/202070923

**Comment by jayvdb** [comment]
`VersionConflict.req` was added in https://github.com/pypa/setuptools/commit/23d5e4a81a61c , v 11.1 - Jan 2015

**Comment by jayvdb** [comment]
However as late as setuptools v16 `import pkg_resources` fails on Python 3.6, echoing problems seen at https://github.com/coala/coala/issues/3745#issuecomment-280189841

See https://travis-ci.org/jayvdb/coala/jobs/202160915#L438

**Comment by jayvdb** [comment]
Traced the pkg_resources vs Python 3.6 problem down to https://github.com/pypa/setuptools/issues/378 , which means setuptools 17 is the first version that works on Python 3.6.

**Comment by jayvdb** [comment]
Note, pyroma (a bear dependency) depends on `setuptools` without any version : https://bitbucket.org/regebro/pyroma/src/13d98d66433061eae5ac5f56216887ebc5547f61/setup.py?at=default&fileviewer=file-view-default#setup.py-32
