### ISSUE TITLE
pip install wheel with extra alldeps fails on pip 6.0.7

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3745]
Using pip 6.0.7 on the Travis precise builds fails.

```
$ pip --version
pip 6.0.7 from /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages (python 3.4)

$ pip install $(ls ./dist/*.whl)"[alldeps]"
..
Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pip/req/req_install.py", line 179, in from_line
    isolated=isolated)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pip/req/req_install.py", line 52, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2873, in parse
    reqs = list(parse_requirements(s))
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2820, in parse_requirements
    "version spec")
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2785, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', './dist/coala_bears-0.10.0.dev99999999999999-py34.py35.py36-none-any.whl[alldeps]', 'at', '/dist/coala_bears-0.10.0.dev99999999999999-py34.py35.py36-none-any.whl[alldeps]')
```
https://travis-ci.org/jayvdb/coala-bears/jobs/201824404

A similar problem has been raised before at https://github.com/coala/coala/issues/1852#issuecomment-221476930

We can at least include a minimum version in `test-requirements.txt`

**Comment by jayvdb** [comment]
pip 7.0 [works](https://travis-ci.org/jayvdb/coala-bears/builds/201841184)
pip 6.0.8 [fails](https://travis-ci.org/jayvdb/coala-bears/builds/201842749)

 setuptools 0.9.8 [fails](https://travis-ci.org/jayvdb/coala-bears/jobs/201857550#L2701) and 7.0 [fails](https://travis-ci.org/jayvdb/coala-bears/jobs/202067566)
with
```
error in coala-bears setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
```

**Comment by jayvdb** [comment]
setuptools 8.0 works for all other versions with coala-bears, but isn't compatible with Python 3.6

```
$ python setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import setuptools.command.build_py
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/setuptools/__init__.py", line 12, in <module>
    from setuptools.extension import Extension
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/setuptools/extension.py", line 8, in <module>
    from .dist import _get_unpatched
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/setuptools/dist.py", line 26, in <module>
    import pkg_resources
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/pkg_resources.py", line 1529, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```
https://travis-ci.org/jayvdb/coala-bears/jobs/202073297#L2640

**Comment by jayvdb** [comment]
For the same reason as https://github.com/coala/coala/issues/3748#issuecomment-280277455 , pip 7.1 is the first to vendor `setuptools`' `pkg_resources` 17+, so pip 7.1 is the first to work on Python 3.6.

See also https://github.com/pypa/pip/pull/2894#issuecomment-280278521
